### ISSUE TITLE
Run on web-camera feed

### ISSUE THREAD

**Issue by TNA8** [kirito12138/AFF-Net#3]
Thanks for your great work.

How can I run the trained AFF-Net on web camera feed?

* Your current model takes 4 inputs; left and right eye images, face images, and `Rect`.
Eye images and face images could be obtained from face landmark detector, but how can I get the `Rect` for a given image? What is the `Rect`?
* The model's output is 2d gaze points on screen. Is there no need camera calibrations for intrinsic and extrinsic(camera-monitor) parameters? If I can get above all 4 inputs for web camera frames, can I directly get the on-screen 2d positions of gaze?

Thanks in advance.

**Comment by kirito12138** [comment]
Hi! Thanks for your interest in our work. 
First, Rect is the up-left and bottom-right corner of each bounding box (left eye, right eye and face bounding box) in pixel coordinates. In practice, the coordinates are divided by 1000 for normalization.
Second, the model output the physical distance between PoG and camera in centimeters (actually, it depends on your training label). Here, we assume the screen plane is perpendicular to the Z axis of camera. So, if you wanna use AFF-Net for web camera, you probably need to calibrate the relative pose between your camera and screen.
