### ISSUE TITLE
Conversion 2d gaze positions into 3d gaze vector

### ISSUE THREAD

**Issue by TNA8** [kirito12138/AFF-Net#4]
You converted the output 2d gaze on-screen positions into 3d gaze vector in camera coordinate system.
![screenshot_99](https://user-images.githubusercontent.com/58914448/145806270-87ea4538-af0b-4491-9953-d96bd2485db5.png)

To do that, extrinsic camera calibration(camera-screen) is needed.
* Could you be more specific about that process?
* Could you share the code for that process too?

Thanks in advance.

**Comment by kirito12138** [comment]
The 3D gaze direction $g_{3D}$ is a direction vector from the center of face (or two eyes) $f$ to the 2D gaze position $g_{2D}$. So, the estimated 3D gaze direction $\hat{g}_{3D}$ can be computed according to estimated 2D gaze position $\hat{g}_{2D}$ and head center $f$ from dataset labels: $\hat{g}_{3D} = f - \hat{g}_{2D}$. All symbols are defined in 3D Camera Coordinate System. Note that $\hat{g}_{3D}$ is a unit vector.
