### ISSUE TITLE
RECTS definition

### ISSUE THREAD

**Issue by wlamers** [kirito12138/AFF-Net#6]
Thank you for your great work!

While running through the paper, code, dataset and the pre-processed 'labels' from newFaceLdmk.json I cannot derive the exact meaning/definition of rects (column 5 in newFaceLdmk.json). Neither dan I find this using the GazeHub processing code.

From the paper I understand 'rects' are the bounding boxes of the face and eyes. The face and eye images are already an input to the model. So I do not understand why using the face bounding box is usefull here. Do we crop the face image again? The face image and eye image indexes are given in pixels whereas the 'rects' are normalized. Are these values given with respect to the origenal image (as an ratio of the width and height)? If so, why would this be usefull for the AFF-net model, since the original image is no input to the model. 

The code for the preprocessing is missing (to generage newFaceLdmk.json), therefore I am stuck. Can you please explain the definition of the 'rects' vector in more detail?

Thank you!

**Comment by kirito12138** [comment]
Thanks for your interest in our work. 
'Rects' are useful since the original image is not fed to the network. To predict PoG, the network needs to know both gaze direction and the distance between the target face and the camera. Since the face image is cropped to the same size, the network can not derive the distance between faces and camera from it. Thus, rects tell the network the location and the size of target faces in the original image, which contains information about where the face is in the Camera Coordinate System. 
It's a common method in PoG prediction methods like the famous paper "Eye Tracking for Everyone".

**Comment by wlamers** [comment]
Thank your quick reply and the explanation, that makes a lot of sense. I went through the earlier paper as well. Still I do not understand how you have preprocessed these 'rects' in newFaceLdmk.json column 5. I plotted these and compared them with the indices used to derive the face and eye images (in red) from the original (see below). Since column 5 is normalized I scaled it to the original image resolution (640x480 in most of the images in GazeCapture). But the rects (in green) do not match the image, nor can I deduct another way how these otherwise would have been calculated. Could you please elaborate how I can calculate these rects myself? Thanks again!

![Screenshot_20220325_092050](https://user-images.githubusercontent.com/18347361/160082180-d0443875-c240-44a4-8440-ef00fd999e06.png)

**Comment by kirito12138** [comment]
We simply divide the pixel coordinates of bounding boxes by 1000. Because in GazeCapture dataset, there are different image resolutions. So, we thought it is better to keep the absolute position of faces and eyes instead of relative positions to the original image.

**Comment by wlamers** [comment]
Thanks that is very helpfull!

It tried to reproduce this but doubt if what I do is then correct. What I get for subject 00099 and frame0 is:
`[669, 502, 204, 377]
[200, 150, 331, 489]
[200, 150, 619, 478]`

for the face, left and right eye respectively. The coordinates from the face are beyond the image resolution itself and the coordinates at index 0 and 1 for the eyes are identical (which is what I see for other frames and subject 'labels' as well). Then I thought maybe these are the centers and width+heights of the bounding boxes, but that does not make sense either. Now I'm lost... Could you explain whats wrong here or would you mind sharing a code snippet of the pre-processing code?

**Comment by kirito12138** [comment]
Really really sorry that I miss the resize part in the last comment... The image needs to be resized to 1000x1000 pixels first. Then, the Rects are defined as [height, width, rows, columns] in . The rows and columns are defined by the the up-left corner of the bounding boxes. 
```
rect = np.array([[669, 502, 204, 377], [200, 150, 331, 489] ,[200, 150, 619, 478]])
img = cv2.imread('00000.jpg')
img = cv2.resize(img, (1000, 1000))
img = cv2.rectangle(img, (int(rect[0][2]), int(rect[0][3])), (int(rect[0][2])+int(rect[0][0]), int(rect[0][3])+int(rect[0][1])), (0, 0, 255))
img = cv2.rectangle(img, (int(rect[1][2]), int(rect[1][3])), (int(rect[1][2]) + int(rect[1][0]), int(rect[1][3]) + int(rect[1][1])), (0, 0, 255))
img = cv2.rectangle(img, (int(rect[2][2]), int(rect[2][3])), (int(rect[2][2]) + int(rect[2][0]), int(rect[2][3]) + int(rect[2][1])), (0, 0, 255))
cv2.imshow('1', img)
cv2.waitKey(0)
```
The above code plots the Rect in the corresponding image:
![image](https://user-images.githubusercontent.com/44642013/160100929-6f893d6d-a0bc-4f72-b6a6-c88c69d1e5e3.png)

The codes are in another server which I can't access recently, sorry that I can't give you the original code directly.

**Comment by wlamers** [comment]
Ok great, thank you, that makes sense!
